export const csvHeaderMap: { [key: string]: string } = {
  Inkomsttyp: 'inkomsttyp',
  Inkomsttypsnamn: 'inkomsttypsnamn',
  Inkomsthuvudgrupp: 'inkomsthuvudgrupp',
  Inkomsthuvudgruppsnamn: 'inkomsthuvudgruppsnamn',
  Inkomsttitelgrupp: 'inkomsttitelgrupp',
  Inkomsttitelgruppsnamn: 'inkomsttitelgruppsnamn',
  Inkomsttitel: 'inkomsttitel',
  Inkomsttitelsnamn: 'inkomsttitelsnamn',
  År: 'år',
  'Statens budget': 'statens_budget',
  Utfall: 'utfall',
  'Inkomsttyp utfallsår': 'inkomsttyp_utfallsår',
  'Inkomsttypsnamn utfallsår': 'inkomsttypsnamn_utfallsår',
  'Inkomsthuvudgrupp utfallsår': 'inkomsthuvudgrupp_utfallsår',
  'Inkomsthuvudgruppsnamn utfallsår': 'inkomsthuvudgruppsnamn_utfallsår',
  'Inkomsttitelgrupp utfallsår': 'inkomsttitelgrupp_utfallsår',
  'Inkomsttitelgruppsnamn utfallsår': 'inkomsttitelgruppsnamn_utfallsår',
  'Inkomsttitel utfallsår': 'inkomsttitel_utfallsår',
  'Inkomsttitelsnamn utfallsår': 'inkomsttitelsnamn_utfallsår',
}
